name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: key.pem
          passphrase: ""
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-frontend
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-backend
            docker-compose down
            docker-compose up -d
